# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rack-gem-assets}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Simon Menke"]
  s.date = %q{2009-11-09}
  s.description = %q{A Middleware for sending assets packaged in loaded gems}
  s.email = %q{simon@mrhenry.be}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "dist/apache/mod_xsendfile.c",
     "lib/rack-gem-assets.rb",
     "lib/rack/gem_assets.rb",
     "rack-gem-assets.gemspec",
     "rails/init.rb",
     "rails/init.rb",
     "test/helper.rb",
     "test/test_rack-gem-assets.rb"
  ]
  s.homepage = %q{http://github.com/simonmenke/rack-gem-assets}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{See description}
  s.test_files = [
    "test/helper.rb",
     "test/test_rack-gem-assets.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

